# Generated by Django 5.2.4 on 2026-06-21 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brightness",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="명도: 밝을수록 높음",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color_family",
            field=models.CharField(
                choices=[
                    ("PINK", "핑크"),
                    ("ROSE", "로즈"),
                    ("CORAL", "코랄"),
                    ("RED", "레드"),
                    ("BERRY", "베리"),
                    ("LAVENDER", "라벤더"),
                    ("BEIGE", "베이지"),
                    ("BROWN", "브라운"),
                    ("GRAY", "그레이"),
                    ("IVORY", "아이보리"),
                    ("ETC", "기타"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="contrast",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="대비감",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="coolness",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="쿨톤 점수",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="depth",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="딥한 정도: 어두울수록 높음",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="finish",
            field=models.CharField(
                choices=[
                    ("MATTE", "매트"),
                    ("GLOSSY", "글로시"),
                    ("VELVET", "벨벳"),
                    ("SHIMMER", "쉬머"),
                    ("NATURAL", "내추럴"),
                    ("UNKNOWN", "미분류"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hex_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="mall_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="naver_category1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="naver_category2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="naver_category3",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="naver_category4",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="naver_product_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="rgb_b",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(255),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rgb_g",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(255),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rgb_r",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(255),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="saturation",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="채도: 선명할수록 높음",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="softness",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="탁도/부드러움: 회색기나 부드러움이 클수록 높음",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="source_query",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="texture",
            field=models.CharField(
                blank=True,
                help_text="예: 립틴트, 립글로스, 아이팔레트, 쿠션, 블러셔, 컬러렌즈",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tone_tag",
            field=models.CharField(
                choices=[
                    ("SPRING_LIGHT", "봄 웜 라이트"),
                    ("SPRING_BRIGHT", "봄 웜 브라이트"),
                    ("SUMMER_LIGHT", "여름 쿨 라이트"),
                    ("SUMMER_MUTE", "여름 쿨 뮤트"),
                    ("AUTUMN_MUTE", "가을 웜 뮤트"),
                    ("AUTUMN_DEEP", "가을 웜 딥"),
                    ("WINTER_BRIGHT", "겨울 쿨 브라이트"),
                    ("WINTER_DEEP", "겨울 쿨 딥"),
                    ("UNKNOWN", "미분류"),
                ],
                default="UNKNOWN",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warmth",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="웜톤 점수",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="review",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
