# Generated by Django 5.2.4 on 2026-06-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0004_diagnosisresult_diagnosed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosisresult",
            name="diagnosis_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="makeup_generation_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="makeup_generation_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="palette_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="palette_status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("preparing", "Preparing"),
                    ("missing", "Missing"),
                ],
                default="ready",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="processed_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="diagnosis/processed/"
            ),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("low_confidence", "Low confidence"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="tone_key",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="personalcolor",
            name="tone_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=80, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="MakeupGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makeup_generation_jobs",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalColorPalette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tone_key",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("tone_name", models.CharField(max_length=80)),
                ("season", models.CharField(max_length=20)),
                ("temperature", models.CharField(max_length=20)),
                ("brightness", models.CharField(max_length=40)),
                ("chroma", models.CharField(max_length=40)),
                ("contrast", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("best_colors", models.JSONField(blank=True, default=list)),
                ("worst_colors", models.JSONField(blank=True, default=list)),
                ("makeup_palette", models.JSONField(blank=True, default=dict)),
                ("base_makeup_guide", models.TextField(blank=True)),
                ("lip_guide", models.TextField(blank=True)),
                ("cheek_guide", models.TextField(blank=True)),
                ("eye_guide", models.TextField(blank=True)),
                ("styling_keywords", models.JSONField(blank=True, default=list)),
                (
                    "recommended_product_tone_range",
                    models.JSONField(blank=True, default=dict),
                ),
                ("is_placeholder", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personal_color",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_palette",
                        to="diagnosis.personalcolor",
                    ),
                ),
            ],
            options={
                "ordering": ["tone_key"],
            },
        ),
    ]
