# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_diagnosisresult_diagnosis_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcolorpalette',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='diagnosiscolorpalette',
            name='group',
            field=models.CharField(
                choices=[
                    ('best', 'Best'),
                    ('neutral', 'Neutral'),
                    ('accent', 'Accent'),
                    ('try', 'Try'),
                    ('worst', 'Worst'),
                ],
                max_length=20,
            ),
        ),
    ]
