# Generated by Codex on 2026-06-22

from django.db import migrations, models


def sync_existing_style_status(apps, schema_editor):
    DiagnosisMakeoverStyle = apps.get_model('diagnosis', 'DiagnosisMakeoverStyle')
    DiagnosisMakeoverStyle.objects.exclude(image__isnull=True).exclude(image='').update(status='complete')


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_personalcolorpalette_data_and_try_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosismakeoverstyle',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosismakeoverstyle',
            name='status',
            field=models.CharField(
                choices=[
                    ('none', 'None'),
                    ('queued', 'Queued'),
                    ('running', 'Running'),
                    ('complete', 'Complete'),
                    ('failed', 'Failed'),
                    ('skipped', 'Skipped'),
                ],
                db_index=True,
                default='none',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='makeupgenerationjob',
            name='style_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.RunPython(sync_existing_style_status, migrations.RunPython.noop),
    ]
