"""
Django settings for Lumiere project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

import dj_database_url

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return

    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


if load_dotenv:
    load_dotenv(BASE_DIR / '.env')
else:
    load_env_file(BASE_DIR / '.env')

if os.getenv('API_KEY') and not os.getenv('OPENAI_API_KEY'):
    os.environ['OPENAI_API_KEY'] = os.getenv('API_KEY')


def env_flag(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=None):
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_BASE_URL = os.getenv('OPENAI_BASE_URL', 'https://gms.ssafy.io/gmsapi/api.openai.com/v1')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4.1')
AI_DIAGNOSIS_MODEL = os.getenv('AI_DIAGNOSIS_MODEL') or OPENAI_MODEL
OPENAI_DIAGNOSIS_MOCK = env_flag('OPENAI_DIAGNOSIS_MOCK')
PRODUCT_ANALYSIS_ENABLE_BROWSER_FETCH = env_flag('PRODUCT_ANALYSIS_ENABLE_BROWSER_FETCH', True)
PRODUCT_ANALYSIS_FETCH_TIMEOUT = int(os.getenv('PRODUCT_ANALYSIS_FETCH_TIMEOUT', '10'))
PRODUCT_ANALYSIS_HTTP_RETRY_ATTEMPTS = int(os.getenv('PRODUCT_ANALYSIS_HTTP_RETRY_ATTEMPTS', '2'))
PRODUCT_IMAGE_ANALYSIS_MODEL = os.getenv(
    "PRODUCT_IMAGE_ANALYSIS_MODEL",
    AI_DIAGNOSIS_MODEL
)
PRODUCT_IMAGE_ANALYSIS_ENABLE_AI = env_flag('PRODUCT_IMAGE_ANALYSIS_ENABLE_AI', True)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-%4xdnn79bgj-znfo^6^5z30bcrtew945)0^f9%#i*_^vel+hk#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag('DEBUG', True)
OPENAI_DIAGNOSIS_FALLBACK_ON_ERROR = env_flag('OPENAI_DIAGNOSIS_FALLBACK_ON_ERROR', DEBUG)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1', 'magda-semianimated-idyllically.ngrok-free.dev',])


# Application definition

INSTALLED_APPS = [
    'accounts', # user app 
    'diagnosis', # 퍼스널 컬러 진단 app
    'products',  # 제품 app 
    'community', # 커뮤니티 app
    'engagements', # 참여 활동 app (wishlist 관리하는 app)
    'rest_framework',
    'corsheaders',
    
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Lumiere.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Lumiere.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.getenv('DATABASE_CONN_MAX_AGE', '600')),
            ssl_require=env_flag('DATABASE_SSL_REQUIRE', not DEBUG),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.getenv('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media')))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'https://lumiere.pppp000310.workers.dev',
        'https://magda-semianimated-idyllically.ngrok-free.dev',

    ],
)

# os 모듈을 사용할 때의 정석 방어 코드
cors_origins_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = cors_origins_str.split(',') if cors_origins_str else []
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'ngrok-skip-browser-warning',  # 프론트엔드에서 보내는 커스텀 헤더 허용
    'authorization',               # JWT 토큰 인증을 위한 헤더 허용
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 1. JWT 인증 (토큰이 헤더에 있으면 이걸로 확인)
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
        # 2. 세션 인증 (쿠키에 세션 ID가 있으면 이걸로 확인)
        'rest_framework.authentication.SessionAuthentication', 
    ],
}
# 중요: 프론트엔드와 쿠키(세션)를 주고받는 것을 허용합니다.
CORS_ALLOW_CREDENTIALS = True

# 중요: 프론트엔드에서 오는 POST 요청을 믿을 수 있도록 CSRF 예외 처리
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'https://lumiere.pppp000310.workers.dev',
        'https://magda-semianimated-idyllically.ngrok-free.dev',
    ],
)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'accounts.User'

# --- Email Settings (SMTP) ---
# 장고가 내장하고 있는 메일 발송 엔진을 사용합니다.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # 구글 우체국 주소
EMAIL_PORT = 587 # 구글이 열어둔 보안 포트
EMAIL_USE_TLS = True # 보안 터널 사용 여부 (필수)

# ★ 수정 필요: host님의 실제 정보로 바꿔주세요!
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

BACKEND_ORIGIN = os.getenv('BACKEND_ORIGIN', 'http://127.0.0.1:8000').rstrip('/')

USE_X_FORWARDED_HOST = env_flag('USE_X_FORWARDED_HOST', not DEBUG)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_flag('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_flag('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_flag('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = env_flag('SECURE_HSTS_PRELOAD', not DEBUG)
