# Generated by Django 5.2.4 on 2026-06-20 13:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.user_profile_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "일반 사용자"),
                    ("MANAGER", "매니저"),
                    ("ADMIN", "관리자"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
